helm-build:
  # Use the official docker image.
  image: alpine/helm:3.17.1
  stage: build
  script:
    - helm template testing .
    - helm package .
    - 'curl --fail-with-body --request POST --user gitlab-ci-token:$CI_JOB_TOKEN -k --form "chart=@cicdlab-chart-0.2.0.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'
  only:
    - main
  tags:
    - kubernetes
