helm-build:
  # Use the official docker image.
  image: alpine/helm:3.17.1
  stage: build
  script:
    - helm template testing .
    - helm package .
    # - ls -la
    # - helm repo add --insecure-skip-tls-verify --username gitlab-ci-token --password ${CI_JOB_TOKEN} ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
    # - helm plugin install https://github.com/chartmuseum/helm-push.git
    - 'curl --fail-with-body --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@cicdlab-chart-0.1.0.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'
  only:
    - main
  tags:
    - kubernetes
