{{- $fullName := include "cicdlab-chart.fullname" . -}}
{{- if eq $.Values.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cicdlab-chart.fullname" . }}
  labels:
    {{- include "cicdlab-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cicdlab-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cicdlab-chart.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cicdlab-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $fullName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.tag.service | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.image.env }}
            {{ toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.image.tag.nginx }}
        - name: nginx-proxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.tag.nginx | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
              {{ if regexMatch "main" $fullName }}
              host: {{ $.Values.domainPrefix }}{{ $.Values.domainName }}
              httpHeaders:
              - name: Host
                value: {{ $.Values.domainPrefix }}{{ $.Values.domainName }}
              {{ end }}
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
              {{ if regexMatch "main" $fullName }}
              host: {{ $.Values.domainPrefix }}{{ $.Values.domainName }}
              httpHeaders:
              - name: Host
                value: {{ $.Values.domainPrefix }}{{ $.Values.domainName }}
              {{ end }}
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}